version: '3.4'

services:
  rocketfin.api:
    image: ${DOCKER_REGISTRY-}rockerfin.api
    build:
      context: .
      dockerfile: RocketFin.Api/Dockerfile
    networks:
      - rocketfi-net
    ports:
      - 5000:80
    environment:
      - DOTNET_ENVIRONMENT=Development
      


networks:
  rocketfi-net:
     driver: bridge
