version: '3.4'

services:
  rocketfin.api:
    image: ${DOCKER_REGISTRY-}rockerfin.api
    build:
      context: .
      dockerfile: RocketFin.Api/Dockerfile
    networks:
      - rocketfi-net
    ports:
      - 5000:80
    environment:
      - DOTNET_ENVIRONMENT=Development
      

  rocketfin-frontend:
    image: rocketfin-frontend:1.0.2
    container_name: rocketfin-frontend
    build:
      context: .
      dockerfile: RocketFin.UI/Dockerfile
    networks:
      - rocketfi-net
    ports:
      - 3000:3000
    depends_on:
      - rocketfin.api
networks:
  rocketfi-net:
     driver: bridge
